
import React from 'react';
import Image from 'next/image';
import Logo from '@/public/Logo.png';

export default function Home() {
  const termsAndConditions = `
Effective and Last Updated: 26th September, 2024

This Site/Application/Services are operated and provided by One7Sports Tech Private Limited,  known under the brand name One7Sports ("Us," "Our," "We," or "One7Sports"). We organize  sports and recreational events and offer an internet-based booking platform for both our events  and those of third parties. Our services include sports coaching, outdoor fitness sessions, a sports  analytics platform, a sports streaming platform, sports training activities, and sports facilities and  venues (collectively referred to as "Primary Services"). Additionally, our Site features a community driven 'Groups & Games' feature, allowing customers to connect with groups and participate in  local sports games ("Secondary Services"). These Terms of Use ("User Terms") constitute a legal  contract between you and us. 

License and Usage 

Subject to these User Terms, One7Sports grants you a non-exclusive, limited, non-transferable,  non-sublicensable, and freely revocable license to use the Service for your personal, non commercial use only, as permitted by the features of the Service. One7Sports reserves all rights  not expressly granted herein. 

Applicability 

These User Terms govern your visit to and use of the Site, whether through a computer, mobile  phone, or any other device, as well as your use of the Service and all information,  recommendations, and/or services provided to you on or through the Site and Service. 

Legal Compliance 

This document is an electronic record under the Information Technology Act, 2000 and its  applicable rules, as well as the provisions pertaining to electronic records in various statutes as  amended by the Information Technology Act, 2000. It is generated by a computer system and  does not require physical or digital signatures. 

User Agreement 

By registering an account with us, you agree to be bound by these User Terms. Please read and  understand these User Terms before using the Site. If you do not accept any of the User Terms,  please do not use the Site or avail any of the Services provided. Your agreement to these User  Terms constitutes a binding contract between you and One7Sports regarding the use of the Site  and Services. 

Player Responsibilities and Liability 

Players are required to use full and appropriate sports gear and equipment while playing on the  booked ground. Failure to comply with this rule may result in injuries or life-threatening incidents. 

The app and ground owner are not liable for any injuries, accidents, or loss of life resulting from  the player's failure to adhere to this requirement. 

Your acceptance of these User Terms also includes your acceptance of our Privacy Policy. 

User Terms 

By accepting these User Terms, you also consent to receive promotional emails and SMS alerts  from One7Sports periodically. 

I. Definitions 

All defined and capitalized terms in these User Terms will have the meanings assigned to them  below: 

• Account: The account created by or for the Customer on the Site for availing the Services. • Additional Fee: Any toll duty, inter-state taxes, etc., not included in the Order Value but  payable to third parties or government authorities for availing Services under Applicable  Law. 

• Applicable Law(s): Includes all applicable statutes, enactments, acts of legislature or  parliament, laws, ordinances, rules, by-laws, regulations, notifications, guidelines,  policies, directions, directives, and orders of any governmental authority, tribunal, or court  of India. 

• Application: The mobile application One7Sports, owned and updated by One7Sports  Tech Private Limited from time to time. 

• Convenience Fee: The fee payable by the Customer to One7Sports for the Services, i.e.,  for availing the technology services offered by One7Sports. This fee is charged on every  Order made through the Site and is exclusive of all applicable taxes. 

• Cancellation Fee: The fee payable for the cancellation of an Order by a Customer, as  outlined in Clause 7 of these User Terms. This fee is exclusive of all applicable taxes. • Customer/you: A person who has an Account. 

• E-Wallet: A pre-paid instrument used to make payments on the Site. 

• Force Majeure Event: Any event arising due to causes beyond the reasonable control of  One7Sports. 

• One7Sports Pass: A pass or reservation (physical or electronic) purchased through the  Site, allowing access to and participation in sports activities or fitness sessions at specified  venues, as per the terms and conditions. 

• Order: The order placed by a Customer to avail the Services facilitated through the Site. • Order Value: The amount in Indian Rupees, reflected on the Site, as the amount payable  for a specific Order. This amount is exclusive of all applicable taxes. 

• Registration Data: May include the present, valid, true, and accurate name, email ID,  phone number, and other information required by One7Sports for registration on the  Application.... • Services: A joint reference to the Primary Services and the Secondary Services. • Site: The Application, the website owned and operated by One7Sports, and any website  owned and developed by One7Sports for specific partners/third-party service providers  to list events/sport sessions or any other software that enables the use of the Application. • Total Fee: Includes the Order Value, the Convenience Fee, the Cancellation Fee, the  Additional Fee, and applicable taxes.

• Venue Membership Plan: A membership plan offered by a venue partner and purchased  through the Site. This plan allows booking and access to specific venues/fitness centres  for sports activities or fitness sessions, as per the terms and conditions of the plan. 

II. Eligibility 

1. Competence to Contract: 

o You are eligible to use the Services only if you are competent to enter into a  binding contract under Applicable Laws. 

2. Age Restrictions: 

o If you reside in a jurisdiction that restricts the use of the Service due to age or the  ability to enter into contracts such as these User Terms, your use of the Services  will bind your legal guardian to these User Terms. 

III. Registration and Account 

1. Account Registration: 

o To access certain password-restricted areas of the Site and use specific Services,  you must successfully register an Account with us. 

2. Compliance and Registration Data: 

o You can register on the Site only after complying with the requirements of this  Clause III and providing your Registration Data. 

3. Accuracy of Information: 

o Ensure that your Registration Data is accurate, complete, current, valid, and true,  and update it as necessary. We bear no liability for false, incomplete, outdated, or  incorrect Registration Data provided by you. 

4. Confidentiality and Responsibility: 

o You are solely responsible for maintaining the confidentiality of your Registration  Data and all activities and transactions occurring through your Account. Your  Account cannot be transferred, assigned, or sold to a third party. We are not liable  for any loss resulting from unauthorized use of your password or Account, with or  without your knowledge. 

5. Account Suspension or Termination: 

o We reserve the right to suspend or terminate your Account immediately and  indefinitely if we believe that the Registration Data or any other data provided by  you is incorrect or false, or if the security of your Account has been compromised,  or for any other reason we find just or equitable. 

6. Permitted Information: 

o Except for Registration Data or other data submitted during the use of any Service  offered through the Site ("Permitted Information"), One7Sports does not want you  to send any confidential or proprietary information to One7Sports on the Site or  otherwise, unless required by Applicable Laws. By accepting these User Terms,  you agree that any information or material provided to One7Sports other than the  Permitted Information will not be considered confidential or proprietary. 

7. Application Compatibility:

o Ensure you download the correct Application for your device. We are not liable if  you do not have a compatible mobile device or download the wrong version of the  Application. We reserve the right to terminate the Service and the use of the  Application if you use the Service or Application with an incompatible or  unauthorized device. 

8. Single Account Policy: 

o You are allowed to open only one Account associated with the Registration Data  provided by you. In case of any unauthorized use of your Account, immediately  contact us at info@one7sports.com. 

9. Account Access Issues: 

o If you are unable to access your Account, inform us at info@one7sports.com and  make a written request to block your Account. We are not liable for unauthorized  transactions made through your Account prior to 72 hours after your written  request to block your Account and shall have no liability in case of a Force Majeure  Event. 

IV. Services 

1. Ordering Services: 

o You may order Our Services using Our Site. Applicable fees will be charged as  per the current pricing schedule. 

2. Total Fee: 

o The Total Fee for the Services will be provided through the Site when the Services  are ordered. Terms regarding minimum quantities and service fees apply as  detailed on the Site. 

3. Service Availability: 

o Services may not be available in all locations due to Applicable Law and other  limitations. We reserve the right to decline Services for any reason at our  discretion. You will not be charged in such circumstances. 

4. Usage Agreement: 

o By using the Site to avail the Service, you agree to: 

▪ Use the Service or download the Application for personal use only and not  resell or assign it to a third party.... ▪ Not use an Account subject to any rights of a person other than you  without appropriate authorization. 

▪ Not harm the Service, Site, or our network in any way. 

▪ Provide One7Sports with requested information and documents related to  the performance of Services. 

▪ Use an authorized network to avail the Service. 

▪ Be aware that requesting Services through messages, the Site, or calling  One7Sports' call centre will incur standard messaging, data, and voice  charges. 

▪ Comply with all Applicable Laws from your domicile and residence  country, and the country, state, or city you are in while using the Site or  Service. 

▪ Comply with the Information Technology Act, 2000, and its rules,  regulations, and guidelines. 

▪ Use our Services according to these User Terms. Violating these terms  may result in disabling or suspending your account, as detailed in the  "Term and Termination" section.

▪ Use our Services only for legal, authorized, and acceptable purposes, and  not assist others in using the Services in ways that violate rights, are illegal,  or inappropriate. 

▪ Keep your device and account safe and secure, and promptly notify us of  any unauthorized use or security breach of your account or our Services. ▪ Authorize One7Sports to send you information, alerts, SMS, and other  messages or calls, even if your number is registered with the National Do  Not Call Registry. You can stop this service by emailing  info@one7sports.com. 

5. Non-Compliance: 

o One7Sports reserves the right to immediately terminate the Service and the use  of the Application or booking on the Site in case of non-compliance with any of the  above requirements. 

o One7Sports may store your information or record your calls for contacting you  regarding Service-related matters. Promptly inform One7Sports of any changes  in the information you provided. 

6. Promotional Information: 

o One7Sports or its authorized representative may provide information about  Services, discounts, and promotions via SMS or email to your registered mobile  number/email ID. You can opt out of these communications by contacting  info@one7sports.com. 

7. Information Rights: 

o You grant One7Sports a non-exclusive, worldwide, perpetual, irrevocable, royalty free, sublicensable right to exercise copyright, publicity, host, store, use, copy,  display, reproduce, adapt, publish, database rights, or any other rights you have  in your information, Posted Content, and Accessed Content. 

o One7Sports can share your information and/or Permitted Information with third  parties. 

8. Tie-Ups and Joint Ventures: 

o One7Sports may enter into tie-ups or joint ventures with other institutions  providing similar services. You consent to such arrangements, and the terms and  conditions herein will apply mutatis mutandis to such tie-ups. 

9. One7Sports Passes and Venue Membership Plan: 

o You may purchase One7Sports Passes and/or Venue Membership Plans through  the Site, subject to terms and conditions detailed on the Site. 

o Access to classes/sessions/events at venue centres identified under your Pass or  Membership Plan is subject to availability and is on a first-come, first-serve basis. o You agree to all terms and conditions (including cancellation and refund terms) of  your pass/membership plan as detailed on the Site and will strictly abide by them  when making bookings. 

o One7Sports retains the right to modify or amend terms and conditions related to  your Pass and/or Membership Plan with prior notification to you via email/SMS or  on the Mobile Application. Continued use of the Site after changes are posted  constitutes your consent and acceptance of those changes.

V. Confirmation of Orders 

1. Order Confirmation: 

o Upon receiving your Order request, One7Sports will either confirm or decline the  Order based on the ability to provide the Service. This will be communicated to  you via SMS or email. 

o If the Order is confirmed, you must check the Order details. If any details are  incorrect, inform us immediately at info@one7sports.com. 

2. Consequences of Delay: 

o You will bear the consequences and damages for any delay caused by your  failure to check the confirmation SMS or email or failure to inform One7Sports of  any incorrect details immediately. 

VI. Payment 

1. Total Fee and Additional Charges: 

o Total Fee: One7Sports will charge you the Total Fee for the Service, which is  determined and may be amended at our sole discretion. 

o Additional Fee: You may incur Additional Fees, which will be part of the Total Fee. o Cancellation Fee: Any applicable Cancellation Fee, as outlined in Clause... VII, will  also be included in the Total Fee. 

o Other Charges: Additional charges incurred for availing the Service in cash, not  included in the Total Fee, may also apply. 

2. Payment Collection: 

o Collection of Total Fee: One7Sports will collect the Total Fee from you at the time  of placing the Order. The venue partner is responsible for issuing a tax invoice  after receiving payment. 

3. Taxes: 

o Tax Responsibilities: All applicable taxes related to the Order Value, Convenience  Fee, Additional Fee, and Cancellation Fee are your responsibility. 

4. Split Payment Service: 

o Co-Payer Arrangement: You may split the Total Fee with one or more Co-Payers  (additional customers) using the Split Payment Service. Each Co-Payer must have  or register an Account on the Site. 

o Payment Instructions: A web link for each Co-Payer to pay their share will be sent  by One7Sports to their registered contact details. 

o Responsibility: It is your responsibility to ensure the Total Fee is paid in full. If any  Co-Payer fails to pay, neither you nor the Co-Payer will be entitled to participate  in the Service. 

5. Payment Methods: 

o E-Wallet Payment: You can pay using an E-Wallet powered by a third-party  Payment Processor. E-Wallet payments are not applicable for Orders placed by  phone or when not logged into your Acc
`;

  return (
    <div className="min-h-screen bg-gray-100 p-8">
      <div className=' mt-[2rem] mx-auto w-[200px] h-[20px]' >
        <Image width={300} height={200} alt='one7sports Logo' src={Logo} />

      </div>
      <h1 className=" mt-[70px] text-4xl font-bold text-center mb-8 tc">Terms and Conditions</h1>
      <div className="bg-white  p-[50px] rounded-lg shadow-lg max-w-3xl mx-auto">
      <p className="whitespace-pre-wrap">{termsAndConditions}</p>
      </div>
    </div>
  );
}
